// GENERATED by scripts/extract-theme.mjs from src/viv_theme.c — do not hand edit.
// the simulator renders from exactly the values the exe draws.
export type ThemeMode = 'dark' | 'light';
export interface Accent { name: string; base: string; hot: string; down: string }

export const ACCENTS: Accent[] = [
  {
    "name": "azure",
    "base": "#1e66e8",
    "hot": "#3b7bee",
    "down": "#1a57c8"
  },
  {
    "name": "teal",
    "base": "#0e9888",
    "hot": "#2fb3a2",
    "down": "#0a7a6e"
  },
  {
    "name": "violet",
    "base": "#7a5af0",
    "hot": "#9378f4",
    "down": "#6348ce"
  },
  {
    "name": "amber",
    "base": "#c77420",
    "hot": "#de8c36",
    "down": "#a85e14"
  },
  {
    "name": "rose",
    "base": "#d6445e",
    "hot": "#e4637a",
    "down": "#b93350"
  }
];

export const DARK_TOKENS: Record<string, string> = {
  "VIV_TK_FACE": "#232328",
  "VIV_TK_NAV_FACE": "#1b1b1f",
  "VIV_TK_CHROME": "#202024",
  "VIV_TK_CHROME_LINE": "#3a3a40",
  "VIV_TK_CHROME_MUTED": "#707070",
  "VIV_TK_FRAME": "#1b1b1e",
  "VIV_TK_INPUT": "#2a2a2f",
  "VIV_TK_LINE": "#3a3a40",
  "VIV_TK_HOVER": "#2e2e33",
  "VIV_TK_DOWN": "#38383e",
  "VIV_TK_TEXT": "#e8e8ea",
  "VIV_TK_TEXT2": "#9a9aa0",
  "VIV_TK_TEXTOFF": "#6a6a70",
  "VIV_TK_ACCENT": "#000000",
  "VIV_TK_ACCENT_HOT": "#000000",
  "VIV_TK_ACCENT_DOWN": "#000000",
  "VIV_TK_ON_ACCENT": "#ffffff"
};
export const LIGHT_TOKENS: Record<string, string> = {
  "VIV_TK_FACE": "#f0f0f0",
  "VIV_TK_NAV_FACE": "#f0f0f0",
  "VIV_TK_CHROME": "#e0e0e0",
  "VIV_TK_CHROME_LINE": "#a0a0a0",
  "VIV_TK_CHROME_MUTED": "#6d6d6d",
  "VIV_TK_FRAME": "#ffffff",
  "VIV_TK_INPUT": "#ffffff",
  "VIV_TK_LINE": "#a0a0a0",
  "VIV_TK_HOVER": "#e3e3e3",
  "VIV_TK_DOWN": "#a0a0a0",
  "VIV_TK_TEXT": "#000000",
  "VIV_TK_TEXT2": "#6d6d6d",
  "VIV_TK_TEXTOFF": "#6d6d6d",
  "VIV_TK_ON_ACCENT": "#ffffff"
};
export const TOKEN_ORDER: string[] = [
  "VIV_TK_FACE",
  "VIV_TK_NAV_FACE",
  "VIV_TK_CHROME",
  "VIV_TK_CHROME_LINE",
  "VIV_TK_CHROME_MUTED",
  "VIV_TK_FRAME",
  "VIV_TK_INPUT",
  "VIV_TK_LINE",
  "VIV_TK_HOVER",
  "VIV_TK_DOWN",
  "VIV_TK_TEXT",
  "VIV_TK_TEXT2",
  "VIV_TK_TEXTOFF",
  "VIV_TK_ACCENT",
  "VIV_TK_ACCENT_HOT",
  "VIV_TK_ACCENT_DOWN",
  "VIV_TK_ON_ACCENT"
];

export function themeColor(mode: ThemeMode, token: string, accent: number): string {
  if (token === 'VIV_TK_ACCENT') return ACCENTS[accent].base;
  if (token === 'VIV_TK_ACCENT_HOT') return ACCENTS[accent].hot;
  if (token === 'VIV_TK_ACCENT_DOWN') return ACCENTS[accent].down;
  return (mode === 'dark' ? DARK_TOKENS : LIGHT_TOKENS)[token] ?? '#ff00ff';
}
