#!/usr/bin/env node
/**
 * extract_theme.mjs — transcribe the C theme table into TypeScript.
 *
 * reads src/viv_theme.c (the single source of the palette) and emits
 * sim/theme-tokens.ts, so the page simulator can never drift from what
 * the exe actually draws (the "mockup vs build" mismatch guard). both
 * sides are parsed now: the dark table's RGB literals and the light
 * switch's returns. a fixed tone crosses as a hex; a GetSysColor entry
 * crosses as a "sys:CONST" marker naming the constant the exe reads at
 * runtime - the simulator's stand-in for those lives in
 * LIGHT_SYS_DEFAULTS (the classic light theme), a documented default
 * rather than a claim about any machine's palette. the audit round
 * found the old hardcoded light copy four tokens stale: a mirror that
 * is typed by hand is a mirror that lies quietly.
 *
 * usage: node scripts/extract-theme.mjs [--check] [repoRoot]
 *   --check    compare sim/theme-tokens.ts against the C tables and
 *              exit 1 on drift, writing nothing.
 *   repoRoot   defaults to the working directory - the documented
 *              invocation (and the ci --check leg) runs from the
 *              repository root, like every other tool here.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const args = process.argv.slice(2);
const checkOnly = args.includes('--check');
const rootArg = args.find((a) => a !== '--check');
const root = rootArg ?? process.cwd();
const src = readFileSync(join(root, 'src/viv_theme.c'), 'utf8');

const byte = (x) => String(x).toLowerCase().replace(/^0x/, '').padStart(2, '0');
const rgb = (r, g, b) => '#' + byte(r) + byte(g) + byte(b);

// parse the dark token table:  RGB(0xRR,0xGG,0xBB),\t// VIV_TK_NAME
const darkRows = [...src.matchAll(/RGB\((0x[0-9A-Fa-f]{2}),(0x[0-9A-Fa-f]{2}),(0x[0-9A-Fa-f]{2})\),?\s*\/\/\s*(VIV_TK_\w+)/g)];
const dark = {};
for (const [, r, g, b, name] of darkRows) dark[name] = rgb(r, g, b);

// parse the light switch inside _viv_theme_light_color: each case
// returns either a fixed RGB literal or a live GetSysColor constant.
const lightZone = src.slice(src.indexOf('_viv_theme_light_color'),
                            src.indexOf('_viv_theme_accent_colors'));
const lightRows = [...lightZone.matchAll(/case (VIV_TK_\w+): return (?:RGB\((0x[0-9A-Fa-f]{2}),(0x[0-9A-Fa-f]{2}),(0x[0-9A-Fa-f]{2})\)|GetSysColor\((\w+)\));/g)];
const light = {};
const sysUsed = new Set();
for (const [, name, r, g, b, sysConst] of lightRows) {
  if (sysConst) {
    light[name] = `sys:${sysConst}`;
    sysUsed.add(sysConst);
  } else {
    light[name] = rgb(r, g, b);
  }
}

// parse the accent table: 5 rows x {base, hot, down}
const accentRows = [...src.matchAll(/\{RGB\((0x\w+),(0x\w+),(0x\w+)\),RGB\((0x\w+),(0x\w+),(0x\w+)\),RGB\((0x\w+),(0x\w+),(0x\w+)\)\},?\s*\/\/\s*(\w+)/g)];
const accents = accentRows.map((m) => ({
  name: m[10],
  base: rgb(m[1], m[2], m[3]),
  hot: rgb(m[4], m[5], m[6]),
  down: rgb(m[7], m[8], m[9]),
}));

// the simulation stand-ins for the live system palette: the classic
// light theme's values. the exe reads the real palette at runtime;
// these are what the page simulator draws when it must draw something.
// a constant the C side newly names must be answered here by hand.
const SYS_DEFAULTS = {
  COLOR_BTNFACE: '#f0f0f0',
  COLOR_MENU: '#f0f0f0',
  COLOR_3DSHADOW: '#a0a0a0',
  COLOR_GRAYTEXT: '#6d6d6d',
  COLOR_WINDOW: '#ffffff',
  COLOR_WINDOWTEXT: '#000000',
};
for (const c of sysUsed) {
  if (!(c in SYS_DEFAULTS)) {
    throw new Error(`no simulation default for ${c} - name one in SYS_DEFAULTS`);
  }
}
const sysDefaults = {};
for (const c of Object.keys(SYS_DEFAULTS)) {
  if (sysUsed.has(c)) sysDefaults[c] = SYS_DEFAULTS[c];
}

const order = [
  'VIV_TK_FACE', 'VIV_TK_NAV_FACE', 'VIV_TK_CHROME', 'VIV_TK_CHROME_LINE', 'VIV_TK_CHROME_MUTED',
  'VIV_TK_FRAME', 'VIV_TK_INPUT', 'VIV_TK_LINE', 'VIV_TK_HOVER', 'VIV_TK_DOWN',
  'VIV_TK_TEXT', 'VIV_TK_TEXT2', 'VIV_TK_TEXTOFF', 'VIV_TK_ACCENT', 'VIV_TK_ACCENT_HOT',
  'VIV_TK_ACCENT_DOWN', 'VIV_TK_ON_ACCENT',
];

const out = `// GENERATED by scripts/extract-theme.mjs from src/viv_theme.c — do not hand edit.
// the simulator renders from exactly the values the exe draws: fixed
// tones cross as hex, and light tokens the exe reads from the live
// system palette cross as "sys:CONST" markers naming the constant -
// LIGHT_SYS_DEFAULTS is the simulator's stand-in for those (the
// classic light theme), not a claim about any machine's palette.
export type ThemeMode = 'dark' | 'light';
export interface Accent { name: string; base: string; hot: string; down: string }

export const ACCENTS: Accent[] = ${JSON.stringify(accents, null, 2)};

export const DARK_TOKENS: Record<string, string> = ${JSON.stringify(dark, null, 2)};
export const LIGHT_TOKENS: Record<string, string> = ${JSON.stringify(light, null, 2)};
export const LIGHT_SYS_DEFAULTS: Record<string, string> = ${JSON.stringify(sysDefaults, null, 2)};
export const TOKEN_ORDER: string[] = ${JSON.stringify(order, null, 2)};

export function themeColor(mode: ThemeMode, token: string, accent: number): string {
  if (token === 'VIV_TK_ACCENT') return ACCENTS[accent].base;
  if (token === 'VIV_TK_ACCENT_HOT') return ACCENTS[accent].hot;
  if (token === 'VIV_TK_ACCENT_DOWN') return ACCENTS[accent].down;
  const v = (mode === 'dark' ? DARK_TOKENS : LIGHT_TOKENS)[token] ?? '#ff00ff';
  if (v.startsWith('sys:')) return LIGHT_SYS_DEFAULTS[v.slice(4)] ?? '#ff00ff';
  return v;
}
`;

if (checkOnly) {
  let current = null;
  try {
    current = readFileSync(join(root, 'sim/theme-tokens.ts'), 'utf8');
  } catch {
    // fall through to the drift report
  }
  if (current !== out) {
    console.error('check: sim/theme-tokens.ts drifted from src/viv_theme.c');
    console.error('run: node scripts/extract-theme.mjs');
    process.exit(1);
  }
  console.log('check: sim/theme-tokens.ts matches src/viv_theme.c');
  process.exit(0);
}

mkdirSync(join(root, 'sim'), { recursive: true });
writeFileSync(join(root, 'sim/theme-tokens.ts'), out);
console.log('theme-tokens.ts written:', order.length, 'tokens,', accents.length, 'accents,',
            Object.keys(light).length, 'light rows (', sysUsed.size, 'runtime system colors )');
console.log('dark sample:', dark['VIV_TK_FACE'], dark['VIV_TK_TEXT'], 'accent0:', accents[0]?.base);
