#!/usr/bin/env node
/**
 * extract_theme.mjs — transcribe the C theme table into TypeScript.
 *
 * reads src/viv_theme.c (the single source of the palette) and emits
 * sim/theme-tokens.ts, so the page simulator can never drift from what the
 * exe actually draws (the "mockup vs build" mismatch guard).
 *
 * usage: node scripts/extract-theme.mjs [repoRoot]
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';

const root = process.argv[2] ?? '/home/z/vivp-remake2';
const src = readFileSync(`${root}/src/viv_theme.c`, 'utf8');

const byte = (x) => String(x).toLowerCase().replace(/^0x/, '').padStart(2, '0');
const rgb = (r, g, b) => '#' + byte(r) + byte(g) + byte(b);

// parse the dark token table:  RGB(0xRR,0xGG,0xBB),\t// VIV_TK_NAME
const darkRows = [...src.matchAll(/RGB\((0x[0-9A-Fa-f]{2}),(0x[0-9A-Fa-f]{2}),(0x[0-9A-Fa-f]{2})\),?\s*\/\/\s*(VIV_TK_\w+)/g)];
const dark = {};
for (const [, r, g, b, name] of darkRows) dark[name] = rgb(r, g, b);

// parse the accent table: 5 rows x {base, hot, down}
const accentRows = [...src.matchAll(/\{RGB\((0x\w+),(0x\w+),(0x\w+)\),RGB\((0x\w+),(0x\w+),(0x\w+)\),RGB\((0x\w+),(0x\w+),(0x\w+)\)\},?\s*\/\/\s*(\w+)/g)];
const accents = accentRows.map((m) => ({
  name: m[10],
  base: rgb(m[1], m[2], m[3]),
  hot: rgb(m[4], m[5], m[6]),
  down: rgb(m[7], m[8], m[9]),
}));

// the light side is a GetSysColor mapping — semantic constants mirrored
// from _viv_theme_light_color.
const light = {
  VIV_TK_FACE: '#f0f0f0',
  VIV_TK_NAV_FACE: '#f0f0f0',
  VIV_TK_CHROME: '#e0e0e0',
  VIV_TK_CHROME_LINE: '#a0a0a0',
  VIV_TK_CHROME_MUTED: '#6d6d6d',
  VIV_TK_FRAME: '#ffffff',
  VIV_TK_INPUT: '#ffffff',
  VIV_TK_LINE: '#a0a0a0',
  VIV_TK_HOVER: '#e3e3e3',
  VIV_TK_DOWN: '#a0a0a0',
  VIV_TK_TEXT: '#000000',
  VIV_TK_TEXT2: '#6d6d6d',
  VIV_TK_TEXTOFF: '#6d6d6d',
  VIV_TK_ON_ACCENT: '#ffffff',
};

const order = [
  'VIV_TK_FACE', 'VIV_TK_NAV_FACE', 'VIV_TK_CHROME', 'VIV_TK_CHROME_LINE', 'VIV_TK_CHROME_MUTED',
  'VIV_TK_FRAME', 'VIV_TK_INPUT', 'VIV_TK_LINE', 'VIV_TK_HOVER', 'VIV_TK_DOWN',
  'VIV_TK_TEXT', 'VIV_TK_TEXT2', 'VIV_TK_TEXTOFF', 'VIV_TK_ACCENT', 'VIV_TK_ACCENT_HOT',
  'VIV_TK_ACCENT_DOWN', 'VIV_TK_ON_ACCENT',
];

const out = `// GENERATED by scripts/extract-theme.mjs from src/viv_theme.c — do not hand edit.
// the simulator renders from exactly the values the exe draws.
export type ThemeMode = 'dark' | 'light';
export interface Accent { name: string; base: string; hot: string; down: string }

export const ACCENTS: Accent[] = ${JSON.stringify(accents, null, 2)};

export const DARK_TOKENS: Record<string, string> = ${JSON.stringify(dark, null, 2)};
export const LIGHT_TOKENS: Record<string, string> = ${JSON.stringify(light, null, 2)};
export const TOKEN_ORDER: string[] = ${JSON.stringify(order, null, 2)};

export function themeColor(mode: ThemeMode, token: string, accent: number): string {
  if (token === 'VIV_TK_ACCENT') return ACCENTS[accent].base;
  if (token === 'VIV_TK_ACCENT_HOT') return ACCENTS[accent].hot;
  if (token === 'VIV_TK_ACCENT_DOWN') return ACCENTS[accent].down;
  return (mode === 'dark' ? DARK_TOKENS : LIGHT_TOKENS)[token] ?? '#ff00ff';
}
`;
mkdirSync(`${root}/sim`, { recursive: true });
writeFileSync(`${root}/sim/theme-tokens.ts`, out);
console.log('theme-tokens.ts written:', order.length, 'tokens,', accents.length, 'accents');
console.log('dark sample:', dark['VIV_TK_FACE'], dark['VIV_TK_TEXT'], 'accent0:', accents[0]?.base);
