//
// Copyright 2026 hesphoros
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//

// Chinese (Simplified) localization
// Save as UTF-8 without BOM.

static const utf8_t *_localization_string_array_zh_cn[LOCALIZATION_ID_COUNT] = 
{
	"简体中文", // LOCALIZATION_ID_LANGUAGE
	"void Image Viewer", // LOCALIZATION_ID_APP_NAME
	"文件(&F)", // LOCALIZATION_ID_FILE
	"打开文件(&O)...", // LOCALIZATION_ID_OPEN_FILE
	"打开文件夹(&F)...", // LOCALIZATION_ID_OPEN_FOLDER
	"打开 Everything 搜索(&S)...", // LOCALIZATION_ID_OPEN_EVERYTHING_SEARCH
	"添加文件(&A)...", // LOCALIZATION_ID_ADD_FILE
	"添加文件夹...", // LOCALIZATION_ID_ADD_FOLDER
	"添加 Everything 搜索...", // LOCALIZATION_ID_ADD_EVERYTHING_SEARCH
	"打开文件位置(&L)...", // LOCALIZATION_ID_OPEN_FILE_LOCATION
	"编辑(&E)...", // LOCALIZATION_ID_EDIT
	"预览(&V)...", // LOCALIZATION_ID_PREVIEW
	"打印(&P)...", // LOCALIZATION_ID_PRINT
	"设为桌面壁纸(&D)", // LOCALIZATION_ID_SET_DESKTOP_WALLPAPER
	"关闭(&C)", // LOCALIZATION_ID_CLOSE
	"删除(&D)", // LOCALIZATION_ID_DELETE
	"删除到回收站", // LOCALIZATION_ID_DELETE_RECYCLE
	"永久删除", // LOCALIZATION_ID_DELETE_PERMANENTLY
	"重命名(&M)", // LOCALIZATION_ID_RENAME
	"属性(&P)", // LOCALIZATION_ID_PROPERTIES
	"退出(&X)", // LOCALIZATION_ID_EXIT
	"编辑(&E)", // LOCALIZATION_ID_EDIT_MENU
	"剪切(&T)", // LOCALIZATION_ID_CUT
	"复制(&C)", // LOCALIZATION_ID_COPY
	"复制文件名", // LOCALIZATION_ID_COPY_FILENAME
	"复制图片(&Y)", // LOCALIZATION_ID_COPY_IMAGE
	"粘贴(&P)", // LOCALIZATION_ID_PASTE
	"顺时针旋转(&K)", // LOCALIZATION_ID_ROTATE_CLOCKWISE
	"逆时针旋转(&N)", // LOCALIZATION_ID_ROTATE_COUNTERCLOCKWISE
	"复制到文件夹(&F)...", // LOCALIZATION_ID_COPY_TO
	"移动到文件夹(&V)...", // LOCALIZATION_ID_MOVE_TO
	"视图(&V)", // LOCALIZATION_ID_VIEW
	"标题栏", // LOCALIZATION_ID_CAPTION
	"边框", // LOCALIZATION_ID_FRAME
	"菜单(&M)", // LOCALIZATION_ID_MENU
	"状态栏(&B)", // LOCALIZATION_ID_STATUS_BAR
	"工具栏(&C)", // LOCALIZATION_ID_CONTROLS
	"布局预设(&P)", // LOCALIZATION_ID_PRESET
	"极简(&M)", // LOCALIZATION_ID_MINIMAL
	"紧凑(&C)", // LOCALIZATION_ID_COMPACT
	"标准(&N)", // LOCALIZATION_ID_NORMAL
	"全屏(&F)", // LOCALIZATION_ID_FULLSCREEN
	"幻灯片放映(&S)", // LOCALIZATION_ID_SLIDESHOW
	"窗口大小(&W)", // LOCALIZATION_ID_VIEW_WINDOW_SIZE
	"50%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_50_PERCENT
	"100%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_100_PERCENT
	"200%", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_200_PERCENT
	"自动调整窗口(&A)", // LOCALIZATION_ID_VIEW_WINDOW_SIZE_AUTO_FIT
	"刷新(&R)", // LOCALIZATION_ID_REFRESH
	"允许窗口缩小(&A)", // LOCALIZATION_ID_ALLOW_SHRINKING
	"保持宽高比(&K)", // LOCALIZATION_ID_KEEP_ASPECT_RATIO
	"填满窗口(&F)", // LOCALIZATION_ID_FILL_WINDOW
	"1:1", // LOCALIZATION_ID_ONE_TO_ONE
	"适应窗口(&B)", // LOCALIZATION_ID_BEST_FIT
	"自由平移缩放(&N)", // LOCALIZATION_ID_PAN_SCAN
	"增大尺寸(&I)", // LOCALIZATION_ID_INCREASE_SIZE
	"减小尺寸(&D)", // LOCALIZATION_ID_DECREASE_SIZE
	"增加宽度(&W)", // LOCALIZATION_ID_INCREASE_WIDTH
	"减小宽度(&W)", // LOCALIZATION_ID_DECREASE_WIDTH
	"增加高度(&H)", // LOCALIZATION_ID_INCREASE_HEIGHT
	"减小高度(&E)", // LOCALIZATION_ID_DECREASE_HEIGHT
	"缩放(&Z)", // LOCALIZATION_ID_ZOOM
	"放大(&I)", // LOCALIZATION_ID_ZOOM_IN
	"缩小(&O)", // LOCALIZATION_ID_ZOOM_OUT
	"重置缩放(&R)", // LOCALIZATION_ID_RESET
	"上移(&U)", // LOCALIZATION_ID_MOVE_UP
	"下移(&D)", // LOCALIZATION_ID_MOVE_DOWN
	"左移(&L)", // LOCALIZATION_ID_MOVE_LEFT
	"右移(&R)", // LOCALIZATION_ID_MOVE_RIGHT
	"左上移动", // LOCALIZATION_ID_MOVE_UP_LEFT
	"右上移动", // LOCALIZATION_ID_MOVE_UP_RIGHT
	"左下移动", // LOCALIZATION_ID_MOVE_DOWN_LEFT
	"右下移动", // LOCALIZATION_ID_MOVE_DOWN_RIGHT
	"居中(&C)", // LOCALIZATION_ID_MOVE_CENTER
	"重置位置(&S)", // LOCALIZATION_ID_PANSCAN_RESET
	"窗口置顶(&T)", // LOCALIZATION_ID_ON_TOP
	"总是置顶(&A)", // LOCALIZATION_ID_ALWAYS
	"播放时置顶(&W)", // LOCALIZATION_ID_WHILE_PLAYING_OR_ANIMATING
	"从不置顶(&N)", // LOCALIZATION_ID_NEVER
	"选项(&O)...", // LOCALIZATION_ID_OPTIONS
	"幻灯片放映(&S)", // LOCALIZATION_ID_SLIDESHOW_MENU
	"播放/暂停(&P)", // LOCALIZATION_ID_PLAY_PAUSE
	"切换间隔(&R)", // LOCALIZATION_ID_RATE
	"缩短间隔(&D)", // LOCALIZATION_ID_DECREASE_RATE
	"加长间隔(&I)", // LOCALIZATION_ID_INCREASE_RATE
	"250 毫秒", // LOCALIZATION_ID_RATE_250_MILLISECONDS
	"500 毫秒", // LOCALIZATION_ID_RATE_500_MILLISECONDS
	"&1 秒", // LOCALIZATION_ID_RATE_1_SECOND
	"&2 秒", // LOCALIZATION_ID_RATE_2_SECONDS
	"&3 秒", // LOCALIZATION_ID_RATE_3_SECONDS
	"&4 秒", // LOCALIZATION_ID_RATE_4_SECONDS
	"&5 秒", // LOCALIZATION_ID_RATE_5_SECONDS
	"&6 秒", // LOCALIZATION_ID_RATE_6_SECONDS
	"&7 秒", // LOCALIZATION_ID_RATE_7_SECONDS
	"&8 秒", // LOCALIZATION_ID_RATE_8_SECONDS
	"&9 秒", // LOCALIZATION_ID_RATE_9_SECONDS
	"1&0 秒", // LOCALIZATION_ID_RATE_10_SECONDS
	"20 秒", // LOCALIZATION_ID_RATE_20_SECONDS
	"30 秒", // LOCALIZATION_ID_RATE_30_SECONDS
	"40 秒", // LOCALIZATION_ID_RATE_40_SECONDS
	"50 秒", // LOCALIZATION_ID_RATE_50_SECONDS
	"1 分钟", // LOCALIZATION_ID_RATE_1_MINUTE
	"自定义...", // LOCALIZATION_ID_CUSTOM
	"动画(&A)", // LOCALIZATION_ID_ANIMATION
	"播放/暂停(&P)", // LOCALIZATION_ID_ANIMATION_PLAY_PAUSE
	"快进(&F)", // LOCALIZATION_ID_ANIMATION_JUMP_FORWARD
	"快退(&B)", // LOCALIZATION_ID_ANIMATION_JUMP_BACKWARD
	"小幅快进(&F)", // LOCALIZATION_ID_ANIMATION_SHORT_JUMP_FORWARD
	"小幅快退(&B)", // LOCALIZATION_ID_ANIMATION_SHORT_JUMP_BACKWARD
	"大幅快进(&F)", // LOCALIZATION_ID_ANIMATION_LONG_JUMP_FORWARD
	"大幅快退(&B)", // LOCALIZATION_ID_ANIMATION_LONG_JUMP_BACKWARD
	"下一帧(&S)", // LOCALIZATION_ID_ANIMATION_FRAME_STEP
	"上一帧(&V)", // LOCALIZATION_ID_ANIMATION_PREVIOUS_FRAME
	"第一帧(&I)", // LOCALIZATION_ID_ANIMATION_FIRST_FRAME
	"最后一帧(&L)", // LOCALIZATION_ID_ANIMATION_LAST_FRAME
	"减慢(&D)", // LOCALIZATION_ID_ANIMATION_DECREASE_RATE
	"加快(&I)", // LOCALIZATION_ID_ANIMATION_INCREASE_RATE
	"恢复默认速度(&E)", // LOCALIZATION_ID_ANIMATION_RESET_RATE
	"导航(&N)", // LOCALIZATION_ID_NAVIGATE
	"下一张(&N)", // LOCALIZATION_ID_NEXT
	"上一张(&P)", // LOCALIZATION_ID_PREVIOUS
	"第一张(&H)", // LOCALIZATION_ID_HOME
	"最后一张(&E)", // LOCALIZATION_ID_END
	"排序(&S)", // LOCALIZATION_ID_SORT
	"按名称(&N)", // LOCALIZATION_ID_SORT_NAME
	"按完整路径(&P)", // LOCALIZATION_ID_SORT_FULL_PATH
	"按大小(&S)", // LOCALIZATION_ID_SORT_SIZE
	"按修改时间(&M)", // LOCALIZATION_ID_SORT_DATE_MODIFIED
	"按创建时间(&C)", // LOCALIZATION_ID_SORT_DATE_CREATED
	"升序(&A)", // LOCALIZATION_ID_SORT_ASCENDING
	"降序(&D)", // LOCALIZATION_ID_SORT_DESCENDING
	"随机顺序", // LOCALIZATION_ID_SHUFFLE
	"跳转到(&J)...", // LOCALIZATION_ID_JUMP_TO
	"帮助(&H)", // LOCALIZATION_ID_HELP
	"帮助(&H)", // LOCALIZATION_ID_HELP_MENU
	"命令行选项(&C)", // LOCALIZATION_ID_COMMAND_LINE_OPTIONS
	"主页(&P)", // LOCALIZATION_ID_HOME_PAGE
	"捐赠(&D)", // LOCALIZATION_ID_DONATE
	"关于(&A)", // LOCALIZATION_ID_ABOUT
	"https://www.voidtools.com/support/voidimageviewer/", // LOCALIZATION_ID_HELP_SUPPORT_URL
	"https://www.voidtools.com/donate/", // LOCALIZATION_ID_HELP_DONATE_URL
	"https://www.voidtools.com/", // LOCALIZATION_ID_HELP_WEBSITE_URL
	"上一张", // LOCALIZATION_ID_TOOLBAR_PREVIOUS_IMAGE_BUTTON
	"下一张", // LOCALIZATION_ID_TOOLBAR_NEXT_IMAGE_BUTTON
	"播放", // LOCALIZATION_ID_TOOLBAR_PLAY_SLIDESHOW_BUTTON
	"暂停", // LOCALIZATION_ID_TOOLBAR_PAUSE_SLIDESHOW_BUTTON
	"适应窗口", // LOCALIZATION_ID_TOOLBAR_BEST_FIT_BUTTON
	"原始大小", // LOCALIZATION_ID_TOOLBAR_ACTUAL_SIZE_BUTTON
	"预加载中", // LOCALIZATION_ID_STATUS_BAR_PRELOAD
	"加载中...", // LOCALIZATION_ID_STATUS_BAR_LOADING
	"找不到文件。", // LOCALIZATION_ID_STATUS_BAR_FILE_NOT_FOUND
	"图片加载失败。", // LOCALIZATION_ID_STATUS_BAR_FAILED_TO_LOAD_IMAGE
	"正在播放幻灯片", // LOCALIZATION_ID_STATUS_BAR_SLIDESHOW_PLAYING
	"位置 %0.3f %0.3f，缩放 %d%% %d%%，宽高比 %0.3f", // LOCALIZATION_ID_STATUS_BAR_POS_ZOOM_FORMAT
	"动画速度 %0.3f", // LOCALIZATION_ID_STATUS_BAR_ANIMATION_RATE_FORMAT
	"幻灯片间隔 %d %s", // LOCALIZATION_ID_STATUS_BAR_SLIDESHOW_RATE_FORMAT
	"分钟", // LOCALIZATION_ID_STATUS_BAR_MINUTES
	"秒", // LOCALIZATION_ID_STATUS_BAR_SECONDS
	"毫秒", // LOCALIZATION_ID_STATUS_BAR_MILLISECONDS
	"void Image Viewer 选项", // LOCALIZATION_ID_OPTIONS_CAPTION
	"常规", // LOCALIZATION_ID_OPTIONS_GENERAL_DIALOG
	"视图", // LOCALIZATION_ID_OPTIONS_VIEW_DIALOG
	"操作", // LOCALIZATION_ID_OPTIONS_CONTROLS_DIALOG
	"语言(&L):", // LOCALIZATION_ID_OPTIONS_LANGUAGE_STATIC
	"自动（跟随系统）", // LOCALIZATION_ID_LANGUAGE_AUTO
	"确定", // LOCALIZATION_ID_OK_BUTTON
	"取消", // LOCALIZATION_ID_CANCEL_BUTTON
	"把设置保存到 %APPDATA%\\voidImageViewer(&S)", // LOCALIZATION_ID_STORE_SETTINGS_APPDATA
	"允许多开(&I)", // LOCALIZATION_ID_ALLOW_MULTIPLE_INSTANCES
	"开始菜单快捷方式(&M)", // LOCALIZATION_ID_STARTMENU_SHORTCUTS
	"文件关联", // LOCALIZATION_ID_ASSOCIATIONS
	"全选(&A)", // LOCALIZATION_ID_CHECK_ALL
	"全不选(&N)", // LOCALIZATION_ID_CHECK_NONE
	"缩小时采样(&S):", // LOCALIZATION_ID_SHRINK_BLIT_MODE_STATIC
	"放大时采样(&M):", // LOCALIZATION_ID_MAGNIFY_BLIT_MODE
	"最近邻", // LOCALIZATION_ID_BLIT_MODE_NEAREST_COMBOBOXITEM
	"双线性", // LOCALIZATION_ID_BLIT_MODE_LINEAR_COMBOBOXITEM
	"自动调整窗口(&Z):", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_STATIC
	"50%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_50_PERCENT_COMBOBOXITEM
	"100%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_100_PERCENT_COMBOBOXITEM
	"200%", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_200_PERCENT_COMBOBOXITEM
	"适应图像", // LOCALIZATION_ID_OPTIONS_VIEW_AUTO_SIZE_WINDOW_AUTO_FIT_COMBOBOXITEM
	"幻灯片放映时动画至少完整播放一次(&P)", // LOCALIZATION_ID_PLAY_ANIMATIONS_ONCE_STATIC
	"预加载下一张图片(&N)", // LOCALIZATION_ID_PRELOAD_NEXT_IMAGE_STATIC
	"缓存上一张图片(&L)", // LOCALIZATION_ID_CACHE_LAST_IMAGE_STATIC
	"窗口背景颜色(&W):", // LOCALIZATION_ID_WINDOWED_BACKGROUND_COLOR_STATIC
	"全屏背景颜色(&F):", // LOCALIZATION_ID_FULLSCREEN_BACKGROUND_COLOR_STATIC
	"左键操作(&L):", // LOCALIZATION_ID_LEFT_CLICK_ACTION_STATIC
	"右键操作(&R):", // LOCALIZATION_ID_RIGHT_CLICK_ACTION_STATIC
	"鼠标滚轮操作(&M):", // LOCALIZATION_ID_MOUSE_WHEEL_ACTION_STATIC
	"命令(&C):", // LOCALIZATION_ID_COMMANDS_STATIC
	"所选命令的设置", // LOCALIZATION_ID_SETTINGS_FOR_SELECTED_COMMAND
	"添加(&A)...", // LOCALIZATION_ID_ADD_KEY_BUTTON
	"编辑(&E)...", // LOCALIZATION_ID_EDIT_KEY_BUTTON
	"移除(&V)", // LOCALIZATION_ID_REMOVE_KEY_BUTTON
	"添加快捷键", // LOCALIZATION_ID_ADD_KEYBOARD_SHORTCUT_CAPTION
	"编辑快捷键", // LOCALIZATION_ID_EDIT_KEYBOARD_SHORTCUT_CAPTION
	"快捷键(&K):", // LOCALIZATION_ID_SHORTCUT_KEY
	"当前占用此快捷键的命令:", // LOCALIZATION_ID_SHORTCUT_KEY_CURRENTLY_USED_BY
	"移除(&V)", // LOCALIZATION_ID_REMOVE
	"设置自定义间隔", // LOCALIZATION_ID_SET_CUSTOM_RATE_CAPTION
	"间隔(&C):", // LOCALIZATION_ID_CUSTOM_RATE_STATIC
	"分钟", // LOCALIZATION_ID_CUSTOM_RATE_MINUTES
	"秒", // LOCALIZATION_ID_CUSTOM_RATE_SECONDS
	"毫秒", // LOCALIZATION_ID_CUSTOM_RATE_MILLISECONDS
	"关于 void Image Viewer", // LOCALIZATION_ID_ABOUT_CAPTION
	"重命名", // LOCALIZATION_ID_RENAME_CAPTION
	"跳转到", // LOCALIZATION_ID_JUMP_TO_TITLE
	"搜索 Everything", // LOCALIZATION_ID_SEARCH_EVERYTHING
	"版权所有 © %d voidtools", // LOCALIZATION_ID_ABOUT_COPYRIGHT_FORMAT
	"support@voidtools.com", // LOCALIZATION_ID_ABOUT_EMAIL
	"www.voidtools.com", // LOCALIZATION_ID_ABOUT_WEBSITE
	"打开图片", // LOCALIZATION_ID_OPEN_IMAGE_CAPTION
	"所有图片文件", // LOCALIZATION_ID_OPEN_ALL_IMAGE_FILES
	"所有文件", // LOCALIZATION_ID_OPEN_ALL_FILES
	"滚动", // LOCALIZATION_ID_OPTIONS_ACTION_SCROLL_COMBOBOXITEM
	"播放/暂停幻灯片", // LOCALIZATION_ID_OPTIONS_ACTION_PLAY_PAUSE_SLIDESHOW_COMBOBOXITEM
	"播放/暂停动画", // LOCALIZATION_ID_OPTIONS_ACTION_PLAY_PAUSE_ANIMATION_COMBOBOXITEM
	"放大", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_IN_COMBOBOXITEM
	"下一张图片", // LOCALIZATION_ID_OPTIONS_ACTION_NEXT_IMAGE_COMBOBOXITEM
	"1:1 平移", // LOCALIZATION_ID_OPTIONS_ACTION_ONE_TO_ONE_SCROLL_COMBOBOXITEM
	"平移/移动窗口", // LOCALIZATION_ID_OPTIONS_ACTION_SCROLL_MOVE_WINDOW_COMBOBOXITEM
	"右键菜单", // LOCALIZATION_ID_OPTIONS_ACTION_CONTEXT_MENU_COMBOBOXITEM
	"缩小", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_OUT_COMBOBOXITEM
	"上一张图片", // LOCALIZATION_ID_OPTIONS_ACTION_PREVIOUS_IMAGE_COMBOBOXITEM
	"缩放", // LOCALIZATION_ID_OPTIONS_ACTION_ZOOM_COMBOBOXITEM
	"下一张/上一张", // LOCALIZATION_ID_OPTIONS_ACTION_NEXT_PREV_COMBOBOXITEM
	"上一张/下一张", // LOCALIZATION_ID_OPTIONS_ACTION_PREV_NEXT_COMBOBOXITEM
	"标题栏格式(&T):", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_STATIC
	"完整路径", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_FULL_PATH_COMBOBOXITEM
	"仅文件名", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_FILENAME_ONLY_COMBOBOXITEM
	"不显示", // LOCALIZATION_ID_OPTIONS_TITLE_BAR_FORMAT_NONE_COMBOBOXITEM
	"Everything 不可用。", // LOCALIZATION_ID_EVERYTHING_NOT_AVAILABLE_MESSAGE
	"添加 Everything 搜索", // LOCALIZATION_ID_EVERYTHING_ADD_EVERYTHING_SEARCH_CAPTION
	"加载 Everything 搜索", // LOCALIZATION_ID_EVERYTHING_LOAD_EVERYTHING_SEARCH_CAPTION
	"随机排序", // LOCALIZATION_ID_RANDOMIZE
	"复制到文件夹", // LOCALIZATION_ID_COPY_TO_CAPTION
	"移动到文件夹", // LOCALIZATION_ID_MOVE_TO_CAPTION
	"位图图像", // LOCALIZATION_ID_ASSOCIATION_DESCRIPTION_BMP
	"GIF 动画图像", // LOCALIZATION_ID_ASSOCIATION_DESCRIPTION_GIF
	"图标文件", // LOCALIZATION_ID_ASSOCIATION_DESCRIPTION_ICO
	"JPEG 图像", // LOCALIZATION_ID_ASSOCIATION_DESCRIPTION_JPEG
	"JPEG 图像", // LOCALIZATION_ID_ASSOCIATION_DESCRIPTION_JPG
	"PNG 图像", // LOCALIZATION_ID_ASSOCIATION_DESCRIPTION_PNG
	"TIFF 图像", // LOCALIZATION_ID_ASSOCIATION_DESCRIPTION_TIF
	"TIFF 图像", // LOCALIZATION_ID_ASSOCIATION_DESCRIPTION_TIFF
	"WebP 图像", // LOCALIZATION_ID_ASSOCIATION_DESCRIPTION_WEBP
	"显示缩放按钮(&Z)", // LOCALIZATION_ID_ZOOM_CONTROLS
	"缩小", // LOCALIZATION_ID_TOOLBAR_ZOOM_OUT_BUTTON
	"放大", // LOCALIZATION_ID_TOOLBAR_ZOOM_IN_BUTTON
	"缩小", // LOCALIZATION_ID_ZOOMUI_TOOLTIP_ZOOM_OUT
	"放大", // LOCALIZATION_ID_ZOOMUI_TOOLTIP_ZOOM_IN
	"另存为(&A)...", // LOCALIZATION_ID_SAVE_AS
	"保存图片", // LOCALIZATION_ID_SAVE_AS_CAPTION
	"保存图片失败", // LOCALIZATION_ID_SAVE_AS_FAILED
	"PNG 图片", // LOCALIZATION_ID_SAVE_AS_PNG
	"JPEG 图片", // LOCALIZATION_ID_SAVE_AS_JPEG
	"BMP 图片", // LOCALIZATION_ID_SAVE_AS_BMP
};
