#define VERSION_YEAR 2026
#define VERSION_MAJOR 1
#define VERSION_MINOR 1
#define VERSION_REVISION 14

#define VERSION_BUILD 72

#define VERSION_TYPE ""

#define VERSION_STRING "1.1.14-rc.4"
